// <auto-generated />
using System;
using AkarDataAccess.Concrete.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AkarDataAccess.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230420115247_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AkarEntities.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GecerliFlg")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 4, 20, 14, 52, 47, 301, DateTimeKind.Local).AddTicks(3464),
                            CreateUser = "BERKAY AKAR",
                            GecerliFlg = true,
                            ModDate = new DateTime(2023, 4, 20, 14, 52, 47, 301, DateTimeKind.Local).AddTicks(5076),
                            ModUser = "BERKAY AKAR",
                            Password = "mberkayakar",
                            UserName = "mberkayakar",
                            UserPhoto = "https://media.licdn.com/dms/image/C4D03AQH0lx3tESYC7w/profile-displayphoto-shrink_800_800/0/1607277130794?e=2147483647&v=beta&t=mWbd1TIxwSp7B_vA_RkHuJi2tvdrMqAj9EvAyIntub0"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 4, 20, 14, 52, 47, 301, DateTimeKind.Local).AddTicks(5929),
                            CreateUser = "BERKAY AKAR",
                            GecerliFlg = true,
                            ModDate = new DateTime(2023, 4, 20, 14, 52, 47, 301, DateTimeKind.Local).AddTicks(5931),
                            ModUser = "BERKAY AKAR",
                            Password = "atelyon",
                            UserName = "atelyon",
                            UserPhoto = "https://media.licdn.com/dms/image/C4D03AQH0lx3tESYC7w/profile-displayphoto-shrink_800_800/0/1607277130794?e=2147483647&v=beta&t=mWbd1TIxwSp7B_vA_RkHuJi2tvdrMqAj9EvAyIntub0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
